### ISSUE TITLE
is_local_data_guard_enabled argument cannot be set to enabled when creating new database

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1828] opened 2023-04-04 14:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_database_autonomous_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

resource "oci_database_autonomous_database" "this" {

.....
source = "NONE"
is_local_data_guard_enabled = true
}

```

### Expected Behavior

the resource should create new database and then enable local data guard, ideally should allow standby on a different subnet with different nsg.

### Actual Behavior

│ Error: 400-InvalidParameter, Operation failed. Cannot enable Autonomous Data Guard during database creation.
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Operation failed. Cannot enable Autonomous Data Guard during database creation.

### Steps to Reproduce

1. create new database and set the local data guard to true
2. `terraform apply`

### Important Factoids

The most fundamental idea of terraform is that the customer code is a blueprint of the infrastructure. the vendor should do most of the heavy lifting on infrastructure deployment which is not the case here.

As is, we have to deploy the same resource the 2nd time to enable local data guard which is NOT the terraform way, but a legacy shell script thinking which is a huge deviation from how terraform should work.

**Comment by navg-orcl** [comment] 2023-05-12 00:18
Today there is a restriction on enabling local dataguard during create. It is not supported and hence it is blocked on the Database Service API.  It is by design.

**Comment by luckeyca** [comment] 2023-06-21 14:41
Hi @navg-orcl, I think you are missing the point. I have NO problem and NO argument with how the database service API is working and how the API is being designed. HOWEVER, what you fail to understand are
1. how terraform, being a declarative programming language SHOULD work
2. Between terraform, being declarative, and database API, being imperative/procedural, there ARE gaps to be bridged which is what the provider supposed to do. In other words, when you develop the terraform resource, you need to put the logic behind to handling all the procedural stuff to make it declarative which is what terraform is about.
3. lastly, in an enterprise environment, we need to package the resource with all the possible argument combinations for all possible use cases into a single standard reusable module for other users to consume. With this argument in the resource works the way like this, how do you propose we should write this into a single module?

similarly, with case like https://github.com/oracle/terraform-provider-oci/issues/1810, it's the same in principle.

**Comment by luckeyca** [comment] 2023-06-21 14:46
And on top of my head, there are two possible fixes in clean terraform way.

1. still leave this argument inside the existing resource. This will require more code, potentially more complex logic, to handle the database creation, then enable local standby after the database is created.
2. create a separate resource for local standby db. The pseudo code will like:

```
resource "oci_database_autonomous_database" "primary" {

.....
source = "NONE"
....
}

resource "oci_database_autonomous_database_local_standby" "this" {
   primary_adb_id = oci_database_autonomous_database.primary.id
   enabled             = true
}
```

**Comment by navg-orcl** [comment] 2023-09-19 22:38
This issue has been fixed with the latest terraform provider. Please verify.

**Closed as completed** 2024-02-05 19:50 UTC
Labels: bug, In-Progress
