### ISSUE TITLE
Apply Tag to Instances using json?

### ISSUE THREAD

**Issue by ksudha88** [oracle/terraform-provider-oci#461] opened 2018-02-27 09:49 UTC
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by rohanbhattacharjee** [comment] 2018-02-27 18:51
We don't support tagging of resources in the current version of the OCI Terraform Provider.
It is high in our list of TODOs though.

**Comment by AlaaShaker** [comment] 2018-03-05 22:42
For the "json" part of your question, there should be no difference between applying tags (or any other operation) using JSON vs. Terraform's HCL syntax. It's just that tagging itself isn't supported at the moment. 

I'm closing this issue as a duplicate of #400 which tracks supporting resource tagging. Please let me know if that doesn't address your issue.

**Closed by AlaaShaker** 2018-03-05 22:42 UTC
Labels: enhancement
