### ISSUE TITLE
Support Remote Peering Connection for VCN Remote Peering

### ISSUE THREAD

**Issue by cgong-github** [oracle/terraform-provider-oci#521] opened 2018-05-02 14:54 UTC
It is great to support VCN local peering with the latest OCI Terraform provider.  

Could we add support for Remote Peering too?

**Comment by parweza** [comment] 2018-05-04 18:33
Thanks for your feed. I have added this in our backlog items to help us prioritize this for upcoming releases of the provider.

**Comment by anandhmahal** [comment] 2018-05-11 05:35
Duplicate of #404

**Comment by codycushing** [comment] 2018-05-12 20:48
Available in release v2.1.8

**Closed by codycushing** 2018-05-12 20:48 UTC
Labels: enhancement
