### ISSUE TITLE
Cannot create instance from both Image OCID or BootVolume backup in same config

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [oracle/terraform-provider-oci#1211] opened 2020-10-16 07:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
020/10/15 16:06:37 [INFO] Terraform version: 0.12.29
2020/10/15 16:06:37 [INFO] Go runtime version: go1.12.13
+ provider.oci v3.97.0
+ provider.template v2.2.0

### Affected Resource(s)
oci.core.instance

### Terraform Configuration Files

```hcl
## Notes
# Creates Services Utility  Windows VM with standard options

locals {
  new_boot_vol_source = {
    source_id               = var.source_ocid == null ? var.instance_defaults.source_ocid : var.source_ocid
    source_type             = "image"
    boot_volume_size_in_gbs = var.boot_vol_size
  }

  boot_vol_from_backup_source = {
    source_id               = length(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups) == 0 ? null : reverse(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups.*.id)[0]
    source_type             = "bootVolume"
    boot_volume_size_in_gbs = null
  }
  

  latest_backup_ocid_bv1  = length(data.oci_core_volume_backups.bv1_backups.volume_backups) == 0 ? null : reverse(data.oci_core_volume_backups.bv1_backups.volume_backups.*.id)[0]

}

## Resource Definition
resource "oci_core_instance" "cmp_utl" {
  count = 1
  #Required
  availability_domain = (element(var.regional_defaults.ad_list, (var.ad_num - 1))).name
  compartment_id      = var.regional_defaults.regional_utility_compartment
  display_name        = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

  shape = "VM.Standard.E3.Flex"
  shape_config {
    # Note: RAM = ocpus x 16GB
    # Note: # of vNICs = ocpus x 2
    ocpus = var.ocpu_count == null ? var.instance_defaults.ocpu_count : var.ocpu_count
  }

  #Optional
  fault_domain = var.fd == null ? var.instance_defaults.fd : var.fd

  source_details {
    source_id               = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.source_id : local.new_boot_vol_source.source_id
    source_type             = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.source_type : local.new_boot_vol_source.source_type
    boot_volume_size_in_gbs = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.boot_volume_size_in_gbs : local.new_boot_vol_source.boot_volume_size_in_gbs
  }

  # Cloudbase Init
  # Refer cloud-init in https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/LaunchInstanceDetails
  metadata = {
    # Base64 encoded YAML based user_data to be passed to cloud-init
    user_data = var.cloud_db_init_script_base64 == null ? var.instance_defaults.cloud_db_init_script_base64 : var.cloud_db_init_script_base64
  }

  create_vnic_details {
    #Required
    subnet_id      = var.subnet_id == null ? var.instance_defaults.subnet_id : var.subnet_id
    hostname_label = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

    #Optional
    assign_public_ip = false
    display_name     = format("%s%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id, "_vnic")

    # Leave as "" for DHCP, otherwise use <regional>_ips.tf to define.
    private_ip             = var.private_ip
    skip_source_dest_check = false

    # Comma separated list of NSGs to apply to this NIC e.g. nsg_ids=[ oci_core_network_security_group.NSG_0CGBAS.id ,oci_core_network_security_group.NSG_0CGVCN.id  ]
    nsg_ids = var.nsg_ids == null ? var.instance_defaults.nsg_ids : var.nsg_ids
  }


  ## Lifecycle Commands
  lifecycle {

    ignore_changes = [
      # Ignore changes to the image definition. We want new instances to 
      # be created with the latest OS image but existing images will be
      # destroyed if the variable is updated unless this field is here.  
      source_details,

      # Ignore changes to the CloudBaseInit script. As above, we don't
      # want existing instances destroyed when we make changes to 
      # the script because it should only be applicable to new instances
      metadata["user_data"]
    ]
  }


  ## Defined Tag Info ##
  ## Add comma sperated tags in addition to the Environment tag, which is required.
  defined_tags = var.environment_tag == null ? merge(var.instance_defaults.environment_tag) : merge(var.environment_tag)

  ## Freeform Tag Info
  ## One on each line for readability. NOTE: These tags affect a lot of automation functionality so be aware of what you add. For example, 
  ## ansible_managed = true will cause ansible to push standard configs and domain join the vm. This may not be desireable in all cases.
  ## role= xxx will set the Role Ansible will use to congire this vm. weblogic_server etc. Uncomment as required. "terraform_managed"
  ## and os= tags are mandatory.

  freeform_tags = {
    # OS Info. For automation platforms
    os = "windows"

    # Terraform Tags
    terraform_managed = "true",

    #Ansible Tags
     ansible_managed = "true",
     role            = "winutil",
     source_region   = var.regional_defaults.regional_unit_shortname,
     instance        = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

  }
}

# cmp_utl Boot Volume Backup Definition
resource "oci_core_volume_backup_policy_assignment" "CMP_backup_policy" {
  asset_id  = oci_core_instance.cmp_utl.*.boot_volume_id[0]
  policy_id = var.backup_policy_id == null ? var.instance_defaults.backup_policy_id : var.backup_policy_id
}

data "oci_core_boot_volume_backups" "boot_vol_backups" {
  #Required
  compartment_id = var.regional_defaults.regional_utility_compartment

  #Optional
  filter {
    name   = "freeform_tags.instance"
    values = [format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)]
  }
  
  filter {
    name   = "state"
    values = ["AVAILABLE"]
  }
}

output "instance_id" {
  value       = oci_core_instance.cmp_utl.*.id
  description = "The id of this instance"
}

```

### Debug Output

Using boot from backup parameter
[Debug output]
https://gist.github.com/AndreasFrangopoulos/81bfc386a2e68b0f16055d7e0402d16a

### Expected Behavior
New Instance created from boot volume backup

### Actual Behavior
404 NotAuthorizedOrNotFound

### Steps to Reproduce
When run with restore_from_latest_backup=false so that a "image" source is used, the Apply executes. When used with restore_from_latest_backup=true so that an existing bootVolume backup is used, you get a 404.

1. `terraform apply`

### Important Factoids
 The plan is perfect so I don't think the Tf config is flawed here (see start of gist) and all the resources referenced in the plan do exist. The executing machine has the right permissions (full modify on entire tenancy).  I have engaged Oracle support because examining the debug output for the image based deploy and the bootVolume backup based deploy shows no major differences so I concluded it was an upstream problem.  However, they are pushing back because they want to see the full request POSTed to the /instance API and the debug output seems to truncate it.  They are saying required fields (subnet_ocid etc.) are missing from the payload which is why it's failing. I believe this isn't the case because examining the image based deploy output shows the same request content.  Hopefully you can help either troubleshoot this or help me somehow see the full request POSTed to the Oracle API so I can pass it on to Oracle support. They have said they cannot use the returned opc_request ID to see the posted request.

**Comment by varmax2511** [comment] 2020-10-16 15:16
Hi @AndreasFrangopoulos -- thanks for reaching out. I don't see an attached gist in the ticket to view. Also you can get debug level logs with detailed HTTP requests using verbose logging
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/troubleshooting#verbose-logging-for-oci-terraform-provider

**Comment by AndreasFrangopoulos** [comment] 2020-10-16 16:21
Hi. Apologies, I fudged the link to the gist. I've updated it now.

Yes I did enable it, the trouble is the output seems truncated so you can't see the whole payload. Which is  part of the reason my ticket with API support stalled. They want to see that you sent the correct request before they troubleshoot the response

**Comment by varmax2511** [comment] 2020-10-16 20:42
Hi @AndreasFrangopoulos -- thanks for the logs. I was able to reproduce the issue with another sample Terraform config. I am able to see the service call and get the same error as in your gist. This appears to be a question for the upstream service. Will you be able to share the last 3 digits of the Oracle Support ticket so I may update my findings to it? 

In the attached gist I see that your SSH public key details seem to be truncating the payload. You may use the below sample TF config to repro the scenario

```
variable "tenancy_ocid" {
}

variable "user_ocid" {
}

variable "fingerprint" {
}

variable "private_key_path" {
}

variable "region" {
}

variable "compartment_ocid" {
}

variable "ssh_public_key_file" {
}

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
}

variable "instance_shape" {
  default = "VM.Standard.E3.Flex"
}

variable "instance_ocpus" {
  default = 1
}

variable "instance_shape_config_memory_in_gbs" {
  default = 1
}

variable "boot_volume_backup_id" {
}

resource "oci_core_instance" "test_instance" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  compartment_id      = var.compartment_ocid
  display_name        = "TestInstance"
  shape               = var.instance_shape

  shape_config {
    ocpus = "${var.instance_ocpus}"
    memory_in_gbs = "${var.instance_shape_config_memory_in_gbs}"
  }

  create_vnic_details {
    subnet_id        = oci_core_subnet.test_subnet.id
    display_name     = "Primaryvnic"
    assign_public_ip = true
    hostname_label   = "tfexampleinstance"
  }

  source_details {
    source_type = "bootVolume"
    source_id = var.boot_volume_backup_id
  }

  metadata = {
    ssh_authorized_keys = file(var.ssh_public_key_file)
    user_data           = base64encode(file("./userdata/bootstrap"))
  }

  freeform_tags = {
    "freeformkey" = "freeformvalue"
  }
  timeouts {
    create = "60m"
  }
}

resource "oci_core_vcn" "test_vcn" {
  cidr_block     = "10.1.0.0/16"
  compartment_id = var.compartment_ocid
  display_name   = "TestVcn"
  dns_label      = "testvcn"
}

resource "oci_core_internet_gateway" "test_internet_gateway" {
  compartment_id = var.compartment_ocid
  display_name   = "TestInternetGateway"
  vcn_id         = oci_core_vcn.test_vcn.id
}

resource "oci_core_default_route_table" "default_route_table" {
  manage_default_resource_id = oci_core_vcn.test_vcn.default_route_table_id
  display_name               = "DefaultRouteTable"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.test_internet_gateway.id
  }
}

resource "oci_core_subnet" "test_subnet" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  cidr_block          = "10.1.20.0/24"
  display_name        = "TestSubnet"
  dns_label           = "testsubnet"
  security_list_ids   = [oci_core_vcn.test_vcn.default_security_list_id]
  compartment_id      = var.compartment_ocid
  vcn_id              = oci_core_vcn.test_vcn.id
  route_table_id      = oci_core_vcn.test_vcn.default_route_table_id
  dhcp_options_id     = oci_core_vcn.test_vcn.default_dhcp_options_id
}

data "oci_identity_availability_domain" "ad" {
  compartment_id = var.tenancy_ocid
  ad_number      = 1
}

```

**Comment by varmax2511** [comment] 2020-10-16 20:51
Hi @AndreasFrangopoulos -- I am able to reproduce the issue you mentioned when trying to use a `bootVolumeBackup` as source for provisioning an instance. But the service supports provisioning an instance by using a boot volume as the source and not a boot volume backup. 
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_instance

```
source_type - (Required) The source type for the instance. Use image when specifying the image OCID. Use bootVolume when specifying the boot volume OCID
```

When I tried launching the instance with an unattached boot volume as source, then the instance provisioning went fine. Below is the config I used to test the scenario. Please let us know if this resolves your issue.
```
variable "tenancy_ocid" {
}

variable "user_ocid" {
}

variable "fingerprint" {
}

variable "private_key_path" {
}

variable "region" {
}

variable "compartment_ocid" {
}

variable "ssh_public_key_file" {
}

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
}

variable "instance_shape" {
  default = "VM.Standard.E3.Flex"
}

variable "instance_ocpus" {
  default = 1
}

variable "instance_shape_config_memory_in_gbs" {
  default = 1
}

variable "boot_volume_backup_id" {
}

resource "oci_core_instance" "test_instance" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  compartment_id      = var.compartment_ocid
  display_name        = "TestInstance"
  shape               = var.instance_shape

  shape_config {
    ocpus = "${var.instance_ocpus}"
    memory_in_gbs = "${var.instance_shape_config_memory_in_gbs}"
  }

  create_vnic_details {
    subnet_id        = oci_core_subnet.test_subnet.id
    display_name     = "Primaryvnic"
    assign_public_ip = true
    hostname_label   = "tfexampleinstance"
  }

  source_details {
    source_type = "bootVolume"
    source_id = var.boot_volume_backup_id
  }

  metadata = {
    ssh_authorized_keys = file(var.ssh_public_key_file)
    user_data           = base64encode(file("./userdata/bootstrap"))
  }

  freeform_tags = {
    "freeformkey" = "freeformvalue"
  }
  timeouts {
    create = "60m"
  }
}

resource "oci_core_vcn" "test_vcn" {
  cidr_block     = "10.1.0.0/16"
  compartment_id = var.compartment_ocid
  display_name   = "TestVcn"
  dns_label      = "testvcn"
}

resource "oci_core_internet_gateway" "test_internet_gateway" {
  compartment_id = var.compartment_ocid
  display_name   = "TestInternetGateway"
  vcn_id         = oci_core_vcn.test_vcn.id
}

resource "oci_core_default_route_table" "default_route_table" {
  manage_default_resource_id = oci_core_vcn.test_vcn.default_route_table_id
  display_name               = "DefaultRouteTable"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.test_internet_gateway.id
  }
}

resource "oci_core_subnet" "test_subnet" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  cidr_block          = "10.1.20.0/24"
  display_name        = "TestSubnet"
  dns_label           = "testsubnet"
  security_list_ids   = [oci_core_vcn.test_vcn.default_security_list_id]
  compartment_id      = var.compartment_ocid
  vcn_id              = oci_core_vcn.test_vcn.id
  route_table_id      = oci_core_vcn.test_vcn.default_route_table_id
  dhcp_options_id     = oci_core_vcn.test_vcn.default_dhcp_options_id
}

data "oci_identity_availability_domain" "ad" {
  compartment_id = var.tenancy_ocid
  ad_number      = 1
}
```

**Comment by varmax2511** [comment] 2020-10-19 03:48
Hi @AndreasFrangopoulos -- is the issue resolved now?

**Comment by AndreasFrangopoulos** [comment] 2020-10-19 10:39
Hi @varmax2511 , I think I see your point. Thanks for getting to the bottom of it so quickly. 
So it appears the lack of functionality on the API side makes creating an Instance from a boot volume backup needlessly complex. We would have to have a separate oci_core_boot_volume resource but set it to conditionally create that only if the restore_from_latest_backup flag is true? Unless you have a more elegant suggestion?

**Comment by AndreasFrangopoulos** [comment] 2020-10-19 13:47
Below is what i've had to do, and it works except that by defining the lifecycle argument in the original file, we could prevent any changes when the Instance already exists. Now, when the flag is set, even if the instance and a boot volume already exist, the Boot Volume resource at the bottom will be created.  We've been driven into this position because of the original problem but now also because you cannot create a new Boot Volume as a separate resource from an image OCID.
```hcl
## Notes
# Creates Services Utility  Windows VM with standard options

locals {
  new_boot_vol_source = {
    source_id               = var.source_ocid == null ? var.instance_defaults.source_ocid : var.source_ocid
    source_type             = "image"
    boot_volume_size_in_gbs = var.boot_vol_size
  }

  # boot_vol_from_backup_source = {
  #   source_id               = length(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups) == 0 ? null : reverse(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups.*.id)[0]
  #   source_type             = "bootVolume"
  #   boot_volume_size_in_gbs = null
  # }

  boot_vol_from_backup_source = {
    source_id               = length(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups) == 0 ? null : oci_core_boot_volume.cmp_boot_volume.*.id[0]
    source_type             = "bootVolume"
    boot_volume_size_in_gbs = null
  }

  latest_boot_vol_backup_ocid = length(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups) == 0 ? null : reverse(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups.*.id)[0]
  latest_backup_ocid_bv1      = length(data.oci_core_volume_backups.bv1_backups.volume_backups) == 0 ? null : reverse(data.oci_core_volume_backups.bv1_backups.volume_backups.*.id)[0]

}

## Resource Definition
resource "oci_core_instance" "cmp_utl" {
  count = 1
  #Required
  availability_domain = (element(var.regional_defaults.ad_list, (var.ad_num - 1))).name
  compartment_id      = var.regional_defaults.regional_utility_compartment
  display_name        = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

  shape = "VM.Standard.E3.Flex"
  shape_config {
    # Note: RAM = ocpus x 16GB
    # Note: # of vNICs = ocpus x 2
    ocpus = var.ocpu_count == null ? var.instance_defaults.ocpu_count : var.ocpu_count
  }

  #Optional
  fault_domain = var.fd == null ? var.instance_defaults.fd : var.fd

  source_details {
    source_id               = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.source_id : local.new_boot_vol_source.source_id
    source_type             = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.source_type : local.new_boot_vol_source.source_type
    boot_volume_size_in_gbs = var.restore_from_latest_backup == true && local.boot_vol_from_backup_source.source_id != null ? local.boot_vol_from_backup_source.boot_volume_size_in_gbs : local.new_boot_vol_source.boot_volume_size_in_gbs
  }

  # Cloudbase Init
  # Refer cloud-init in https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/LaunchInstanceDetails
  metadata = {
    # Base64 encoded YAML based user_data to be passed to cloud-init
    user_data = var.cloud_db_init_script_base64 == null ? var.instance_defaults.cloud_db_init_script_base64 : var.cloud_db_init_script_base64
  }

  create_vnic_details {
    #Required
    subnet_id      = var.subnet_id == null ? var.instance_defaults.subnet_id : var.subnet_id
    hostname_label = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

    #Optional
    assign_public_ip = false
    display_name     = format("%s%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id, "_vnic")

    # Leave as "" for DHCP, otherwise use <regional>_ips.tf to define.
    private_ip             = var.private_ip
    skip_source_dest_check = false

    # Comma separated list of NSGs to apply to this NIC e.g. nsg_ids=[ oci_core_network_security_group.NSG_0CGBAS.id ,oci_core_network_security_group.NSG_0CGVCN.id  ]
    nsg_ids = var.nsg_ids == null ? var.instance_defaults.nsg_ids : var.nsg_ids
  }


  ## Lifecycle Commands
  lifecycle {

    ignore_changes = [
      # Ignore changes to the image definition. We want new instances to 
      # be created with the latest OS image but existing images will be
      # destroyed if the variable is updated unless this field is here.  
      source_details,

      # Ignore changes to the CloudBaseInit script. As above, we don't
      # want existing instances destroyed when we make changes to 
      # the script because it should only be applicable to new instances
      metadata["user_data"]
    ]
  }


  ## Defined Tag Info ##
  ## Add comma sperated tags in addition to the Environment tag, which is required.
  defined_tags = var.environment_tag == null ? merge(var.instance_defaults.environment_tag) : merge(var.environment_tag)

  ## Freeform Tag Info
  ## One on each line for readability. NOTE: These tags affect a lot of automation functionality so be aware of what you add. For example, 
  ## ansible_managed = true will cause ansible to push standard configs and domain join the vm. This may not be desireable in all cases.
  ## role= xxx will set the Role Ansible will use to congire this vm. weblogic_server etc. Uncomment as required. "terraform_managed"
  ## and os= tags are mandatory.

  freeform_tags = {
    # OS Info. For automation platforms
    os = "windows"

    # Terraform Tags
    terraform_managed = "true",

    #Ansible Tags
    ansible_managed = "true",
    role            = "winutil",
    source_region   = var.regional_defaults.regional_unit_shortname,
    instance        = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

  }
}

# cmp_utl Boot Volume Backup Definition
resource "oci_core_volume_backup_policy_assignment" "CMP_backup_policy" {
  asset_id  = oci_core_instance.cmp_utl.*.boot_volume_id[0]
  policy_id = var.backup_policy_id == null ? var.instance_defaults.backup_policy_id : var.backup_policy_id
}

data "oci_core_boot_volume_backups" "boot_vol_backups" {
  #Required
  compartment_id = var.regional_defaults.regional_utility_compartment

  #Optional
  filter {
    name   = "freeform_tags.instance"
    values = [format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)]
  }

  filter {
    name   = "state"
    values = ["AVAILABLE"]
  }
}

resource "oci_core_boot_volume" "cmp_boot_volume" {
  #Create only if restoring from backup
  count = var.restore_from_latest_backup == true && length(data.oci_core_boot_volume_backups.boot_vol_backups.boot_volume_backups) != 0 ? 1 : 0

  availability_domain = (element(var.regional_defaults.ad_list, (var.ad_num - 1))).name
  compartment_id      = var.regional_defaults.regional_utility_compartment
  source_details {
    #Required
    id   = local.latest_boot_vol_backup_ocid
    type = "bootVolumeBackup"
  }

  backup_policy_id = var.backup_policy_id == null ? var.instance_defaults.backup_policy_id : var.backup_policy_id
  display_name     = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)
  ## Defined Tag Info ##
  ## Add comma sperated tags in addition to the Environment tag, which is required.
  defined_tags = var.environment_tag == null ? merge(var.instance_defaults.environment_tag) : merge(var.environment_tag)

  ## Freeform Tag Info
  freeform_tags = {
    # OS Info. For automation platforms
    os = "windows"

    # Terraform Tags
    terraform_managed = "true",

    #Ansible Tags
    ansible_managed = "true",
    role            = "winutil",
    source_region   = var.regional_defaults.regional_unit_shortname,
    instance        = format("%s%s%s%s", var.regional_defaults.regional_unit_shortname, var.ad_num, "CWSVC", var.instance_id)

  }

}

output "instance_id" {
  value       = oci_core_instance.cmp_utl.*.id
  description = "The id of this instance"
}

```

**Comment by varmax2511** [comment] 2020-10-21 07:16
Hi @AndreasFrangopoulos -- based on the above comments. This is now a problem not in the terraform provider but to build a solution in terraform that can achieve: 
- provisioning instance using imahe
- create a boot volume from the latest boot volume backup available
- provision instance from the boot volume thus created

We can try implementing a workaround in terraform but that's as good as it gets. In the above, when flag is unset, deletion of  `bootVolume` resource in the end should be expected since you wish to have the bootVolume created from the latest bootVolumebackup.  Also the flag should be set only when the instance is down. 
We can share your request for support for this feature to the upstream service.

**Comment by AndreasFrangopoulos** [comment] 2020-10-21 10:37
Morning @varmax2511 , thanks for the response.

To your point about the flag, yes I understand - to be honest I don't necessarily want it, it was just there as a potential workaround.  I would welcome any solution.

If you could put an upstream request that would be great, it would add some weight to it.  I feel like this is a problem many of your customers are likely to face since deploying an instance from a recent backup is a fairly basic requirement. I'll be forwarding this to our account manager as well so perhaps he can raise it in whatever channels he has access to as well.

Thanks for your help. I guess we can close this for now

**Comment by varmax2511** [comment] 2020-10-23 23:07
Sure, we have raised an enhancement request to the upstream service.

**Comment by ravinitp** [comment] 2023-05-04 08:05
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.

**Closed by ravinitp** 2023-05-04 08:05 UTC
Labels: enhancement, core
