### ISSUE TITLE
invalid or unknown key: boot_volume_size_in_gbs

### ISSUE THREAD

**Issue by lhy2828** [oracle/terraform-provider-oci#526] opened 2018-05-10 08:14 UTC
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
$Terraform v0.11.7

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
$terraform-provider-oci 0.0.0
</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>
When i use boot_volume_size_in_gb in source_details,it is error with following error message
"Error: oci_core_instance.TFInstance: source_details.0: invalid or unknown key: boot_volume_size_in_gb"

**Comment by briangustafson** [comment] 2018-05-10 23:46
It looks like you're missing an "s" on the end of the property name "boot_volume_size_in_gbs" - see https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/instances.md.

**Comment by lhy2828** [comment] 2018-05-11 01:43
Thanks for your response
Actually,i had tried "boot_volume_size_in_gbs" ,it also not work
"Error: oci_core_instance.TFInstance: source_details.0: invalid or unknown key: boot_volume_size_in_gbs"

**Comment by kohashim** [comment] 2018-05-15 22:47
@lhy2828 can you share your TF config?  I cannot reproduce this issue.  The "boot_volume_size_in_gbs" was recognized with no issues in my test TF config.

**Comment by kohashim** [comment] 2018-05-15 22:55
@lhy2828 which version of OCI terraform provider are you using?  The attribute "boot_volume_size_in_gbs" was added recently and is supported from v2.1.6.

**Comment by anandhmahal** [comment] 2018-05-21 05:39
@lhy2828 - looks like you are in Oracle Linux and have a terraform setup prior to v2.1.6 and the `boot_volume_size_gbs` was addressed in v2.1.6.  

Terraform versions prior to v2.1.6 in Oracle Linux installed through OL yum repo did not get a version number.  If you are using the OL yum repo, follow these steps to update to the latest version:
1) Uninstall terraform and OCI provider.  Delete local copy of OCI provider plugin from the `<project>/.terraform/plugins` folder (if any) in all of your projects
2) Install the latest version from the OL yum repo.

**Comment by codycushing** [comment] 2018-07-03 03:55
Please let us know if you are not able to resolve the issue.

**Closed by codycushing** 2018-07-03 03:55 UTC
Labels: investigate
