### ISSUE TITLE
Block Volumes cannot attached to instance correctly as expected.

### ISSUE THREAD

**Issue by zhanglei5337** [oracle/terraform-provider-oci#465] opened 2018-03-07 08:22 UTC
### Terraform Version

Terraform v0.11.0
+provider.null v1.0.0
+provider.oci v2.0.4

### Description:
Steps to reproduce:
1. terraform apply 2 instance of oci.
2. each instance need to attach 2 block volumes
3. From oci UI, the 2 block volumes are attached to the instance, but login to the instance to see its disk, The 2 block volumes are not exist (sometimes only 1 is created, sometimes 3 volumes are created, sometimes it is 2...)
4.This issue cannot be reproduced every time . But it always happen.

[volume.xlsx](https://github.com/oracle/terraform-provider-oci/files/1788320/volume.xlsx)

**Comment by michaelhart** [comment] 2018-03-19 19:57
Hi @zhanglei5337, I'm not able to reproduce this issue. It sounds potentially related to #297. If you are able to update to a newer version of the provider, can you confirm if you still experience this issue?

**Comment by zhanglei5337** [comment] 2018-03-20 03:06
Hi @michaelhart,  thank you for your replay ,  I will try it if possible.

**Comment by alexng-canuck** [comment] 2018-03-22 01:28
Hi @zhanglei5337,
Are you still seeing this issue with the latest provider? 
If so, are you using the ISCSI commands to attach the block volumes within the instance?

For example:
```
sudo iscsiadm -m node -o new -T <iqn> -p <ip address>
sudo iscsiadm -m node -o update -T <iqn> -n node.startup -v automatic
sudo iscsiadm -m node -T <iqn> -p <ip address> -l
```

**Comment by zhanglei5337** [comment] 2018-03-28 03:06
Hi @alexng-canuck ,

**Comment by zhanglei5337** [comment] 2018-03-28 03:09
Hi @alexng-canuck ,

No, We are trying to reproduce this issue with the latest provider.
And yes ,we use the ISCSI commands to attach the block volumes.

Thanks.

**Comment by zhanglei5337** [comment] 2018-04-04 02:40
Hi @michaelhart @AlaaShaker ,

I didn't meet this issue with terraform0.11.3, and terraform-provider-ociv2.1.2.

Thanks,
Lei.

**Comment by zhanglei5337** [comment] 2018-05-23 06:19
Hi,

We need to update the  terraform-provider-oci version to the newest for the new feature. 
Then we met this issue again with version 2.1.5 and 2.1.7.
So can you help us to follow this issue again?

Thanks,
Lei.

**Comment by alexng-canuck** [comment] 2018-05-23 17:04
Hi @zhanglei5337 ,

Can you share the Terraform config that you used to reproduce this? Is it still the same as the one that you shared with us initially?

Also, can you share the commands you used to check the number of attached volumes after logging in?

Thanks,
Alex

**Comment by zhanglei5337** [comment] 2018-05-24 06:45
Hi @alexng-canuck ,

Thank you for your reply. I attached the commands, please confirm whether it is what you want.

Thanks,
Lei.
[issue.xlsx](https://github.com/oracle/terraform-provider-oci/files/2034113/issue.xlsx)

**Comment by orclsnikitin** [comment] 2018-06-11 21:27
@zhanglei5337 Would it be possible to get the text source of the templates you used? Inside of the "issue.xlsx" uploaded to GitHub are only images which have been cropped, so I'm unable to see/reproduce the configuration in entirety.

If you have any other advice on how we can reproduce this issue, that would be very helpful. So far I haven't had any luck in my own attempts to reproduce.

**Comment by briangustafson** [comment] 2018-07-23 21:50
@zhanglei5337 Closing, since we have not been able to reproduce. However, if this is still an issue and you can provide the info requested, then please let us know and we can reopen the investigation.

**Closed by briangustafson** 2018-07-23 21:50 UTC
Labels: bug, investigate, need more info
