### ISSUE TITLE
change of freeform_tags in db_home initiate destroy/replace of db_system

### ISSUE THREAD

**Issue by PeterP55P** [oracle/terraform-provider-oci#1213] opened 2020-10-21 13:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v3.97.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

oci_database_db_system

### Terraform Configuration Files

no code needed. 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Debug Output

  # module.databases["tst"].oci_database_db_system.db_system must be replaced

      ~ db_home {
          + database_software_image_id  = (known after apply)
          + db_home_location            = (known after apply)
          ~ db_version                  = "19.8.0.0.0" -> "19.0.0.0"
          ~ defined_tags                = {} -> (known after apply)
            display_name                = "DB01"
          **~ freeform_tags               = { # forces replacement**

### Expected Behavior
freeform_tags at any place shouldn't initiate of entire db_system

### Actual Behavior
change in freeform_tags within db_home section initiates to replace the entire db_system which indeed destroys the entire database and recreates it. that is definitely not expected behavior. 

### Steps to Reproduce
1. create a db_system
2. change freeform_tags within db_home section
3. terraform apply 

1. `terraform apply`

**Comment by govindrao55** [comment] 2020-10-23 01:20
Hi @PeterP55P , the `db_home` fields are not updatable via `oci_database_db_system` resource by design, though making tags updatable via `oci_database_db_system` is something I think we should consider. I've created internal ticket for that. 
You can still import the DBHome resource and manage it separately. In case the tags were added to `db_home` during the `db_system` creation and if you now wish to import and manage the nested resources separately, you will have to use [ingore_changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to suppress the diff on `oci_database_db_system` resource. e.g.
```
resource "oci_database_db_system" "test_db_system" {
    db_home {
        freeform_tags = {
          "dymmyKey" = "dummyValue"
        }
    }
    ...
    lifecycle {
        ignore_changes = [
          db_home.0.freeform_tags,
        ]
    }
}
```

**Comment by PeterP55P** [comment] 2020-10-26 16:09
Hi @govindrao55 , thanks for the response. Yes, I used the workaround but I believe that freeform_tags shouldn't initiate recreate of any resource.  Thanks for putting this on a list for further implementation. 

Peter

**Comment by mstaffa** [comment] 2021-09-15 14:29
Hello,

We are currently experiencing the same behavior. DB systems created as part of a custom module are attempting to rebuild the entire DB system because the tags were changed.

The above workaround was successful, however the behavior doesn't make much sense. Please make this a priority, as DB systems already take upwards of 1.5-3 hours to provision in OCI.

Thank you

**Comment by ravinitp** [comment] 2023-04-24 13:58
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.

**Closed by ravinitp** 2023-04-24 13:58 UTC
Labels: bug, responded
