### ISSUE TITLE
BMCS Provider with Chef Provisioner...?

### ISSUE THREAD

**Issue by lfeldman** [oracle/terraform-provider-oci#32] opened 2017-03-17 18:15 UTC
Is it possible to nest chef provisioner or any other Terraform provisioner within the body of BMCS Provider resources?

For example such snippet seems to be not working. During resource creation both provisioners have been omitted...

resource "baremetal_core_instance" "terraform_webserver1" {
  availability_domain = "${var.ADs[0]}"
  compartment_id = "${baremetal_identity_compartment.terraform_compartment.id}"
  display_name = "WebServer1"
  image = "${var.Images[0]}"
  shape = "${var.Shapes[0]}"
  subnet_id = "${baremetal_core_subnet.terraform_Subnet1.id}"
  metadata {
    ssh_authorized_keys = "${var.ssh_auth_key2}"
  }
  provisioner "local-exec" {
     command = "echo ${self.private_ip_address} > file.txt"
  }
  provisioner "chef" {
    node_name = "terraform_webserver1"
    server_url = "https://chefserver.ora1521.org/organizations/oraorg"
    user_name = "ora1521"
    user_key = "${file("/Users/lukaszfeldman/chef/ora1521.pem")}"
    run_list = ["cookbook::recipe"]
  }
}

**Comment by craigcarl-oracle** [comment] 2017-03-23 21:04
Yes, the challenge is that the vNIC is an entirely different resource than the instance so the IP of the instance isn't returned when the instance is launched. We're exploring options.

**Comment by lfeldman** [comment] 2017-03-24 18:03
What is strange it looks like to work now... 

```
MacBook-Pro-Lukasz:start_tfs_v1.0 lukaszfeldman$ more webserver1.tf 
resource "baremetal_core_instance" "terraform_webserver1" {
  availability_domain = "${var.ADs[0]}"
  compartment_id = "${baremetal_identity_compartment.terraform_compartment.id}"
  display_name = "WebServer1"
  image = "${var.Images[0]}"
  shape = "${var.Shapes[0]}"
  subnet_id = "${baremetal_core_subnet.terraform_Subnet1.id}"
  metadata {
      ssh_authorized_keys = "${file("/Users/lukaszfeldman/chef/chefserver__id_rsa.pub")}"
  }
}

data "baremetal_core_vnic_attachments" "w1_vnic_attach" {
  availability_domain = "${var.ADs[0]}"
  compartment_id = "${baremetal_identity_compartment.terraform_compartment.id}"
  instance_id = "${baremetal_core_instance.terraform_webserver1.id}"
}

data "baremetal_core_vnic" "w1_vnic" {
  vnic_id = "${data.baremetal_core_vnic_attachments.w1_vnic_attach.vnic_attachments.0.vnic_id}"
}

resource "null_resource" "terraform_webserver1_ready" {
  triggers {
    webserver1_ready_id = "${baremetal_core_instance.terraform_webserver1.id}"
    chefserver_ready_id = "${baremetal_core_instance.terraform_chefserver.id}"
  }
  depends_on = ["null_resource.terraform_chefserver_ready"]
  provisioner "local-exec" {
     command = "scp -i /Users/lukaszfeldman/chef/chefserver__id_rsa -o 'StrictHostKeyChecking no' *.pem opc@${data.baremetal_core_vnic.w1_vnic.public_ip_address}:/home/opc/"
  }
  provisioner "remote-exec" {
        connection {
                type     = "ssh"
                user     = "opc"
                host     = "${data.baremetal_core_vnic.w1_vnic.public_ip_address}"
                private_key = "${file("/Users/lukaszfeldman/chef/chefserver__id_rsa")}"
                agent = false
        }
  inline = ["sudo -u root cp /home/opc/ora1521.pem /etc/chef/ora1521.pem",
            "sudo -u root cp /home/opc/ora1521-validator.pem /etc/chef/client.pem",
            "sudo /bin/su -c \"echo '${data.baremetal_core_vnic.w1_vnic.public_ip_address} webserver1.oraorg.org webserver1' >> /etc/hosts\"",
            "sudo /bin/su -c \"echo '${data.baremetal_core_vnic.chef_dbv.public_ip_address} chefserver.oraorg.org chefserver' >> /etc/hosts\"",
            "sudo /bin/su -c \"echo HOSTNAME=webserver1.oraorg.org >> /etc/sysconfig/network\"",
            "sudo -u root hostname webserver1.oraorg.org"]
  }
  provisioner "remote-exec" {
        connection {
                type = "ssh"
                user = "opc"
                host = "${data.baremetal_core_vnic.chef_dbv.public_ip_address}"
                private_key = "${file("/Users/lukaszfeldman/chef/chefserver__id_rsa")}"
                agent = false
        }
    inline = ["sudo /bin/su -c \"echo '${data.baremetal_core_vnic.w1_vnic.public_ip_address} webserver1.oraorg.org webserver1' >> /etc/hosts\""]
  }

  provisioner "chef" {
     connection {
                type     = "ssh"
                user     = "opc"
                host     = "${data.baremetal_core_vnic.w1_vnic.public_ip_address}"
                private_key = "${file("/Users/lukaszfeldman/chef/chefserver__id_rsa")}"
                agent = false
     }
     node_name       = "webserver1"
     server_url      = "https://chefserver.oraorg.org/organizations/oraorg"
     user_name       = "ora1521"
     user_key        = "${file("ora1521.pem")}"
     run_list        = []
     ssl_verify_mode = ":verify_none"
  }


}

```

**Comment by VAdamec** [comment] 2017-06-02 07:03
I can confirm that it works with actual version, IMHO because vnic don't need to be defined as separate resource now.

```
resource "baremetal_core_instance" "test-ad1" {
....
  provisioner "remote-exec" {
    inline = [
      "whoami"
    ]
    connection {
      type     = "ssh"
      user     = "tester"
      host     = "${baremetal_core_instance.test-ad1.private_ip}"
      private_key = "${file("<path_to_key>")}"
    }
  }
}
```

**Comment by josephholsten** [comment] 2017-06-16 19:16
@VAdamec does that mean this is safe to close?

**Comment by VAdamec** [comment] 2017-06-19 09:02
@josephholsten I didn't test Chef, just common remote-exec, @lfeldman can you test it and close this if it's ok ?

**Comment by codycushing** [comment] 2017-09-14 19:33
We have a good example of this now in the docs
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/compute/omc_monitored_server/chef_stage_and_monitor_instance/main.tf

**Closed by codycushing** 2017-09-14 19:33 UTC
Labels: enhancement

**Comment by briangustafson** [comment] 2017-10-09 17:43
We have a second example that uses Chef without OMC, see https://github.com/oracle/terraform-provider-oci/tree/master/docs/examples/compute/instance_chef.
