### ISSUE TITLE
getting strange errors from the data_guard_association

### ISSUE THREAD

**Issue by eugsim1** [oracle/terraform-provider-oci#1275] opened 2021-01-15 18:19 UTC
Hello team
I trying to setup a dataguard on a basic Vm deployment but after 30 minutes terraform craches with the following error :

```
Error: unexpected state 'TERMINATING', wanted target 'AVAILABLE'. last error: %!s(<nil>), The service for this resource encountered an unknown error. Provide the following resource ID if you contact support for help with that service: ocid1.dgassociation.oc1.eu-frankfurt-1.abtheljr7etp3oxomhz5irdljc3vxc2njrfhhrbcqd63sqzl2xy7jdapxq4a

  on modules/db_systems/main.tf line 130, in resource "oci_database_data_guard_association" "dbcs_guard_association":
 130: resource "oci_database_data_guard_association" "dbcs_guard_association" {


[oracle@localhost dbcs-bastion]$ Error: unexpected state 'TERMINATING', wanted target 'AVAILABLE'. last error: %!s(<nil>), The service for this resource encountered an unknown error. Provide the following resource ID if you contact support for help with that service: ocid1.dgassociation.oc1.eu-frankfurt-1.abtheljr7etp3oxomhz5irdljc3vxc2njrfhhrbcqd63sqzl2xy7jdapxq4a
Error: unexpected state 'TERMINATING', wanted target 'AVAILABLE'. last error: %sqlplus sys/BEstrO0ng_#12@130.61.174.18:1521/mydbcs_fra132.lbpbreg.lbvcn1.oraclevcn.com  as sysdba(<nil>), The service for this resource encountered an unknown error. Provide the following resource ID if you contact support for help with that service: ocid1.dgassociation.oc1.eu-frankfurt-1.abtheljr7etp3oxomhz5irdljc3vxc2njrfhhrbcqd63sqzl2xy7jdapxq4a

```
the source ddatabase is available the target database not , the target node is created the script is very basic :
```
+ resource "oci_database_data_guard_association" "dbcs_guard_association" {
      + apply_lag                        = (known after apply)
      + apply_rate                       = (known after apply)
      + availability_domain              = "oTOh:EU-FRANKFURT-1-AD-1"
      + creation_type                    = "NewDbSystem"
      + database_admin_password          = (sensitive value)
      + database_id                      = "ocid1.database.oc1.eu-frankfurt-1.abtheljrnzubstn4esekkfcr6aro5ut2sxghlsg5uohbg75sdfibo6mgi52a"
      + delete_standby_db_home_on_delete = "true"
      + display_name                     = "dgmyoracledb"
      + hostname                         = "dgmyoracledb"
      + id                               = (known after apply)
      + lifecycle_details                = (known after apply)
      + nsg_ids                          = [
          + "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaanrb4kg2skhlkrcg6ifjrv45hgqvvxgndhye7m5qanem5sjlwinq",
          + "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaajh26ceodlsbsgygary3m7s2j2ab36pjg7mk6i4gbvnasjvok4a6q",
        ]
      + peer_data_guard_association_id   = (known after apply)
      + peer_database_id                 = (known after apply)
      + peer_db_home_id                  = (known after apply)
      + peer_db_system_id                = (known after apply)
      + peer_role                        = (known after apply)
      + peer_vm_cluster_id               = (known after apply)
      + protection_mode                  = "MAXIMUM_PERFORMANCE"
      + role                             = (known after apply)
      + shape                            = "VM.Standard2.1"
      + state                            = (known after apply)
      + subnet_id                        = "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaa6z6ytg2h2ve2cvs5sm5i5e5syiuojatngzhtskgvanh2gnnewhq"
      + time_created                     = (known after apply)
      + transport_type                   = "ASYNC"
    }
```
i have setupg ngs and the ports 1521, 1522, 1523, 22 are open, i m working in the same region , same compartment, same AD, the passwords are the same, same shape "VM.Standard2.1" the source db is  "ENTERPRISE_EDITION".

see below the full description of the vm dbcs :
```
dbcs_system        = [
      - {
          - availability_domain                     = "oTOh:EU-FRANKFURT-1-AD-1"
          - backup_network_nsg_ids                  = []
          - backup_subnet_id                        = ""
          - cluster_name                            = ""
          - compartment_id                          = "ocid1.compartment.oc1..aaaaaaaakflr6popkgcfxehemfvkbuhdjhra67v5rilxiut332jofgzjpclq"
          - cpu_core_count                          = 1
          - data_storage_percentage                 = 80
          - data_storage_size_in_gb                 = 256
          - database_edition                        = "ENTERPRISE_EDITION"
          - db_home                                 = []
          - db_system_options                       = [
              - {
                  - storage_management = "LVM"
                },
            ]
          - defined_tags                            = {
              - "Oracle-Tags.CreatedBy"          = "oracleidentitycloudservice/eugene.simos@oracle.com"
              - "Oracle-Tags.ResourceAllocation" = "DataSafe-prep"
            }
          - disk_redundancy                         = "NORMAL"
          - display_name                            = "myoracledb"
          - domain                                  = "lbpbreg.lbvcn1.oraclevcn.com"
          - fault_domains                           = [
              - "FAULT-DOMAIN-2",
            ]
          - freeform_tags                           = {
              - "Comment"     = "Bastion setup for omc project"
              - "Project"     = "omc"
              - "Responsible" = "put the name here"
              - "Role"        = "Bastion for omc"
              - "Version"     = "0.0.0.0"
            }
          - hostname                                = "myoracledb"
          - id                                      = "ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljrtvcpeb45vkmf6pgimbqq3drlw3vlosw7xwtkp2otncgzrojthjjq"
          - iorm_config_cache                       = []
          - kms_key_id                              = ""
          - kms_key_version_id                      = ""
          - last_maintenance_run_id                 = ""
          - last_patch_history_entry_id             = ""
          - license_model                           = "BRING_YOUR_OWN_LICENSE"
          - lifecycle_details                       = ""
          - listener_port                           = 1521
          - maintenance_window                      = []
          - maintenance_window_details              = []
          - next_maintenance_run_id                 = ""
          - node_count                              = 1
          - nsg_ids                                 = [
              - "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaajh26ceodlsbsgygary3m7s2j2ab36pjg7mk6i4gbvnasjvok4a6q",
              - "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaanrb4kg2skhlkrcg6ifjrv45hgqvvxgndhye7m5qanem5sjlwinq",
            ]
          - point_in_time_data_disk_clone_timestamp = ""
          - private_ip                              = ""
          - reco_storage_size_in_gb                 = 256
          - scan_dns_record_id                      = ""
          - scan_ip_ids                             = []
          - shape                                   = "VM.Standard2.1"
          - source                                  = ""
          - source_db_system_id                     = ""
          - sparse_diskgroup                        = false
          - ssh_public_keys                         = [
              - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtcUXIMzcK9tGupINHokVcsNlV21KD7RTJUAL3rKDGRlCR4xwyQ61xsUIcsTf9tIsc8g1UqBc8NrVuCEXopzNTDSGKg9t0d/zkBocaVxJN5EawZAqW5+lNJidrGPGsEA7O+LjvJeCZhhhQJbNxV8yra9r5UceZKjQTGUUXn5cTST6Vy5UyDZTVG8cVmk8QGTfGwsgzardCa1ho/VMJHgCB1dmWEUpEOfc4ou61s7tHMarxXxkgysWYoUtddg/FRUTf0ehf0h2D1v10tc/THNwtpuVmYO2cbLP5BZYYKHmWdymIRFkr33dXqJSu2lipZoFZVL2Rtd+PmEZ03u+uD7Jfw== rsa-key-20201110",
            ]
          - state                                   = "AVAILABLE"
          - subnet_id                               = "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaa6z6ytg2h2ve2cvs5sm5i5e5syiuojatngzhtskgvanh2gnnewhq"
          - time_created                            = "2021-01-15 15:50:59.105 +0000 UTC"
          - time_zone                               = "Europe/Helsinki"
          - version                                 = ""
          - vip_ids                                 = []


```

```
the dbcs_database      = [
      ~ {
          ~ character_set                                    = "AL32UTF8" -> (known after apply)
          ~ compartment_id                                   = "ocid1.compartment.oc1..aaaaaaaakflr6popkgcfxehemfvkbuhdjhra67v5rilxiut332jofgzjpclq" -> (known after apply)
          ~ connection_strings                               = [
              - {
                  - all_connection_strings = {
                      - "cdbDefault"   = "myoracledb.lbpbreg.lbvcn1.oraclevcn.com:1521/mydbcs_fra1bb.lbpbreg.lbvcn1.oraclevcn.com"
                      - "cdbIpDefault" = "(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.1.2)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=mydbcs_fra1bb.lbpbreg.lbvcn1.oraclevcn.com)))"
                    }
                  - cdb_default            = "myoracledb.lbpbreg.lbvcn1.oraclevcn.com:1521/mydbcs_fra1bb.lbpbreg.lbvcn1.oraclevcn.com"
                  - cdb_ip_default         = "(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.1.2)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=mydbcs_fra1bb.lbpbreg.lbvcn1.oraclevcn.com)))"
                },
            ] -> (known after apply)
          ~ database                                         = null -> (known after apply)
          ~ database_software_image_id                       = null -> (known after apply)
          ~ db_backup_config                                 = [
              - {
                  - auto_backup_enabled        = false
                  - auto_backup_window         = ""
                  - backup_destination_details = []
                  - recovery_window_in_days    = 0
                },
            ] -> (known after apply)
          ~ db_home_id                                       = "ocid1.dbhome.oc1.eu-frankfurt-1.abtheljrrojmumbvfhxcsffmtivk7ym3gjqttgiboqg2hw7weoe23nhgojbq" -> (known after apply)
          ~ db_name                                          = "mydbcs" -> (known after apply)
          ~ db_system_id                                     = "ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljrtvcpeb45vkmf6pgimbqq3drlw3vlosw7xwtkp2otncgzrojthjjq" -> (known after apply)
          ~ db_unique_name                                   = "mydbcs_fra1bb" -> (known after apply)
          ~ db_version                                       = null -> (known after apply)
          ~ db_workload                                      = "OLTP" -> (known after apply)
          ~ defined_tags                                     = {
              - "Oracle-Tags.CreatedBy"          = "oracleidentitycloudservice/eugene.simos@oracle.com"
              - "Oracle-Tags.ResourceAllocation" = "DataSafe-prep"
            } -> (known after apply)
          ~ freeform_tags                                    = {
              - "Comment"     = "Bastion setup for omc project"
              - "Project"     = "omc"
              - "Responsible" = "put the name here"
              - "Role"        = "Bastion for omc"
              - "Version"     = "0.0.0.0"
            } -> (known after apply)
          ~ id                                               = "ocid1.database.oc1.eu-frankfurt-1.abtheljrnzubstn4esekkfcr6aro5ut2sxghlsg5uohbg75sdfibo6mgi52a" -> (known after apply)
          ~ kms_key_id                                       = null -> (known after apply)
          ~ kms_key_migration                                = null -> (known after apply)
          ~ kms_key_rotation                                 = null -> (known after apply)
          ~ kms_key_version_id                               = null -> (known after apply)
          ~ last_backup_timestamp                            = null -> (known after apply)
          ~ lifecycle_details                                = null -> (known after apply)
          ~ ncharacter_set                                   = "AL16UTF16" -> (known after apply)
          ~ pdb_name                                         = "pdbName" -> (known after apply)
          ~ source                                           = null -> (known after apply)
          ~ source_database_point_in_time_recovery_timestamp = null -> (known after apply)
          ~ state                                            = "AVAILABLE" -> (known after apply)
          ~ time_created                                     = "2021-01-15 15:50:59.11 +0000 UTC" -> (known after apply)
          ~ vm_cluster_id                                    = null -> (known after apply)
            # (1 unchanged element hidden)
        },
```

do you see any issues on these settings ?
this is full reproducible

**Comment by zexinwanoci** [comment] 2021-01-19 16:59
Hello @eugsim1 , can you also share the request id and the type of the request and the associated resource type? (get/post/etc ) From this error it seems like a service internal error causing the crash rather then a terraform issue.

**Comment by rashik-bhasin** [comment] 2021-01-19 19:43
Can you please share the full terraform config file that you are using for us to reproduce this and also details as to which provider version are you using and the terraform version.
Thanks!

**Comment by ravinitp** [comment] 2023-04-24 13:57
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.

**Closed by ravinitp** 2023-04-24 13:57 UTC
Labels: bug, database
