### ISSUE TITLE
Provider for Darwin_arm64

### ISSUE THREAD

**Issue by flavius-dinu** [oracle/terraform-provider-oci#1322] opened 2021-03-15 09:57 UTC
### Description

At the moment, there is no available provider for Apple M1 processor.
I believe there are many developers that switched to this platform and having support for this, will make our lives easier.

```
Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/oci v4.17.0 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by srishtipmishra** [comment] 2021-03-18 13:57
@flavius-dinu - Thanks for reporting this. This is on our roadmap and we are planning this to coincide when there is an official M1 version of Terraform Core from HashiCorp. Let us know if you have more questions.

**Comment by cablespaghetti** [comment] 2021-06-11 08:51
@srishtipmishra The latest terraform releases now have arm builds and other providers have added support by simply upgrading to Go 1.16 e.g. https://github.com/Mongey/terraform-provider-kafka/pull/173/files

It looks like this provider might depend on the deprecated `hashicorp/template` provider which doesn't have an ARM build, so work would also need to be done to move over to https://github.com/hashicorp/terraform-provider-cloudinit

**Comment by rafee** [comment] 2021-09-01 17:28
@srishtipmishra any timeline on the provider support for arm64?

**Comment by unencoded** [comment] 2021-10-05 19:30
Any updates?

**Comment by bhavicp** [comment] 2021-11-07 09:42
Hi, this is a major blocker for us as new joiners are getting new M1 laptops - Any update on this? All other major providers have got darwin_arm64 builds now.

**Comment by nitesh8860** [comment] 2021-11-19 08:31
Hello, Any updates on this, this is major blocker to develop natively on M1 Mac.

**Comment by ivandelic** [comment] 2021-12-01 13:49
Workaround in the meantime: https://ivan-delic.medium.com/oci-terraform-provider-for-apple-m1-52bdbce9c83c

**Comment by rafee** [comment] 2021-12-07 18:26
While it's good that @ivandelic provided an easy solution, it brings more questions than answers. If the steps are as simple as just compiling it on a M1 Mac, what's stopping Oracle from doing it? I initially thought it's dependency issue (i.e. it uses some packages as dependency, which are still not ported to darwin_arm64). However, given Apple is fully committed to ARM machines now, it makes no sense from Oracle perspective to delay the support for new machines.

**Comment by bpourian** [comment] 2021-12-14 09:45
"ALL THE THINGS!!!"

**Comment by chucre** [comment] 2021-12-14 09:50
@srishtipmishra the Terraform Core v1.0.2 already support darwin_arm64. There's any update to add this request to the official support for the module?

**Comment by rafee** [comment] 2022-01-23 01:23
#1512 was created to support this initiative. Encouraging everyone to vote there.

**Comment by nitesh8860** [comment] 2022-01-24 06:17
It's about to be an year for this request and we are still building it manually in 2022.

**Comment by SamuelBagattin** [comment] 2022-01-24 17:17
Yep the issue is still there.
I built and published mine.
https://registry.terraform.io/providers/SamuelBagattin/oci/latest

**Comment by vrmurthy** [comment] 2022-01-24 19:52
@SamuelBagattin @nitesh8860 @chucre The work has started to support this, it will soon be available.

**Comment by norberto-enomoto** [comment] 2022-02-14 02:59
Thanks @SamuelBagattin.

**Comment by adamcstephens** [comment] 2022-03-06 20:32
This issue was resolved almost two weeks ago with the release of v4.64.0: https://github.com/terraform-providers/terraform-provider-oci/pull/1522#issuecomment-1047169314

It seems sadly appropriate for this issue that it wasn't updated. At least the darwin-arm64 builds are finally available.

**Comment by rafee** [comment] 2022-03-06 21:21
@srishtipmishra This might be a good time to close this issue.

**Closed** 2023-05-04 07:50 UTC
Labels: enhancement

**Comment by ravinitp** [comment] 2023-05-04 08:00
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
