### ISSUE TITLE
When will you have support for Remote VCN Peering?

### ISSUE THREAD

**Issue by gmflau** [oracle/terraform-provider-oci#494] opened 2018-03-27 04:07 UTC
Wonder when there will be support for Remote VCN Peering.

**Comment by tjkervin** [comment] 2018-03-27 14:06
We would also like this functionality to exist.

**Comment by kohashim** [comment] 2018-03-30 18:47
We are trucking the feature request at #404.  At this point I'm afraid we don't have any concrete date, but this is one of our highest priority items.  Thank you for your patience.  Closing as duplicate of #404.

**Closed by kohashim** 2018-03-30 18:47 UTC
Labels: duplicate, enhancement
